var TravellrFeedItem = new Class({

		Extends: FeedItem,

		data: null,

		content: null,
		preview: null,

		initialize: function() {
			this.question = this.questions.getRandom();
			delete this.questions;

			this.question.safe_subject = this.question.subject.toLowerCase().replace(/[^a-z0-9]*/, '-').replace(/^-|-$/, '');
			this.question.url = 'http://travellr.com/questions/place/' + this.question.id + '/' + this.question.safe_subject;

			this.size = {x: $random(1, 4), y: $random(1, 4)};
		},

		makePreview: function() {
			return new Element('div', {'class': 'travellr'}).adopt([
					new Element('p', {text: this.question.subject}),
			]);
		},
		makeContent: function() {
			return new Element('div', {'class': 'travellr'}).adopt([
					new Element('h2').grab(new Element('a', {text: this.question.subject, href: this.question.url})),
					new Element('p').adopt(this.question.content.newlineToBr()),
					new Element('p', {'class': 'date', text: Date.parse(this.question.created_at).toString()})
			]);
		},


		questions: [
			{id:7,person_id:5,location_id:5130,subject:"How much does it cost to travel in Thailand?",content:"I hear it's really cheap....how much does it cost roughly for:\ra) food\rb) accomodation\rc) transport - and what's the best way to get around?",tags:"food",created_at:"2009-02-03 10:58:44",last_answer:"2009-02-04 04:12:21",location_shard:"thailand",answer_count:1,tags_plaintext:"food"},
			{id:9,person_id:4,location_id:5130,subject:"Where are the best dive spots?",content:"I am headed to Thailand in a few week and am looking to do some dive courses, where is good? I am happy to travel arond a bit to make sure I get the good spots...",tags:"dive",created_at:"2009-02-03 11:03:07",last_answer:"2009-02-12 06:40:28",location_shard:"thailand",answer_count:3,tags_plaintext:"diving"},
			{id:11,person_id:5,location_id:5130,subject:"What is cell phone and internet access like in Thailand?",content:"I need to work while I'm away - what's the best and cheapest way to connect?",tags:"work",created_at:"2009-02-03 11:43:43",last_answer:"2009-02-12 06:19:12",location_shard:"thailand",answer_count:3,tags_plaintext:"working"},
			{id:16,person_id:7,location_id:5156,subject:"What are the best golf courses in Bangkok?",content:"I am thinking about heading over to Bangkok for a holiday, and wanted to know what good golf courses were available to tourists.",tags:"",created_at:"2009-02-03 12:22:46",last_answer:"2009-02-26 18:49:08",location_shard:"thailand",answer_count:2,tags_plaintext:""},
			{id:21,person_id:5,location_id:5130,subject:"Can I get advice about renting cars or motorbikes?",content:"What should I expect to pay? Are there any catches or things I should look out for?",tags:"",created_at:"2009-02-03 12:52:02",last_answer:"2009-02-04 03:41:36",location_shard:"thailand",answer_count:1,tags_plaintext:"motorbike"},
			{id:43,person_id:5,location_id:5130,subject:"Can someone recommend a really good eco experience in Thailand?",content:"",tags:"",created_at:"2009-02-05 23:36:30",last_answer:"2009-08-14 04:52:14",location_shard:"thailand",answer_count:3,tags_plaintext:""},
			{id:44,person_id:5,location_id:5143,subject:"What's a good day activity in Chiang Mai?",content:"",tags:"",created_at:"2009-02-05 23:37:42",last_answer:"2010-02-02 12:08:14",location_shard:"thailand",answer_count:7,tags_plaintext:""},
			{id:45,person_id:5,location_id:5156,subject:"Can someone recommend a good hotel in Bangkok?",content:"Nothing over the top, but clean, comfortable and well-situated.",tags:"",created_at:"2009-02-05 23:39:19",last_answer:"2009-09-12 09:07:04",location_shard:"thailand",answer_count:8,tags_plaintext:""},
			{id:46,person_id:5,location_id:5156,subject:"What is a good hotel close to the airport for an overnight stopover in Bangkok?",content:"",tags:"",created_at:"2009-02-05 23:40:04",last_answer:"2009-05-30 05:34:07",location_shard:"thailand",answer_count:3,tags_plaintext:""},
			{id:47,person_id:5,location_id:5141,subject:"What is a good restaurant on Koh Lanta?",content:"Someplace affordable, but with good authentic food. Also, how much should I expect to pay?",tags:"restaur food",created_at:"2009-02-05 23:42:08",last_answer:"2009-02-08 13:40:32",location_shard:"thailand",answer_count:1,tags_plaintext:"restaurants, food"},
			{id:77,person_id:88,location_id:5156,subject:"What is the best way to get to the tiger temple from Bangkok? train, bus or taxi?",content:"the tiger temple is a monastery where some monks have grown some tigers into domesticated animals, apparently its a really good place to visit whilst in Thailand, and we are heading over in the next month..",tags:"templ",created_at:"2009-02-09 23:15:53",last_answer:"2009-09-12 09:28:40",location_shard:"thailand",answer_count:4,tags_plaintext:"temples"},
			{id:78,person_id:88,location_id:5205,subject:"whats the best way from phuket to malaysia? train or plane?",content:"",tags:"",created_at:"2009-02-09 23:18:33",last_answer:"2009-02-12 03:14:25",location_shard:"thailand",answer_count:2,tags_plaintext:""},
			{id:90,person_id:80,location_id:5156,subject:"Can anyone recommend a good tailor\/s near Sukhumvit Road?",content:"Heading to Thailand for a few weeks in June and want to get some clothes made. Would like to make sure I get a reputable tailor to make them...have heard stories of some using glue instead of stitching which I would like to avoid! Will be staying in the Sukhumvit area...",tags:"cloth",created_at:"2009-02-10 10:34:14",last_answer:"2010-02-17 05:40:56",location_shard:"thailand",answer_count:11,tags_plaintext:"clothing"},
			{id:159,person_id:261,location_id:5156,subject:"2 Days in Bangkok - What should I do??",content:"Am arriving in Bangkok on 3rd March before heading South. What are the \\\"Must See's\\\" both during the day, and in the evening. I'm not really looking for red light recommendations as thats pretty much all anybody else has been able to come up with so far elsewhere.\r\rAlso any good mid level hotels I should be aware of close to all the action areas??",tags:"",created_at:"2009-02-19 12:18:10",last_answer:"2009-03-07 11:23:50",location_shard:"thailand",answer_count:5,tags_plaintext:""},
			{id:169,person_id:88,location_id:5130,subject:"Best diving spots through SE Thialand",content:"Heading for a dive adventure to learn to scuba, thinking of Krabi\/Thailand, but am interested in a location that is not too full of tourists and middle aged sunbakers...",tags:"",created_at:"2009-02-24 10:01:01",last_answer:"2009-02-24 10:21:41",location_shard:"thailand",answer_count:2,tags_plaintext:""},
			{id:170,person_id:10,location_id:5130,subject:"I need some info on transport in Thailand.",content:"I am thinking about a trip to Thailand in April and think I might do it on the cheap and by myself.\rI heard the trains are quite good there.\rWhat are the easy to catch trains, where do you buy tickets and what are the costs?",tags:"",created_at:"2009-02-25 06:11:59",last_answer:"2009-03-11 11:11:05",location_shard:"thailand",answer_count:3,tags_plaintext:"cheap, buying"},
			{id:171,person_id:175,location_id:5205,subject:"Anyone know of how to get from Koh Samui to Phuket??",content:"I would imagine a ferry to the mainland would be the first step, but I need to know which part of the mainland to head to and how to travel from there. Are there buses or trains heading that way??? And how long will it take?",tags:"",created_at:"2009-02-26 00:47:45",last_answer:"2009-02-26 16:20:04",location_shard:"thailand",answer_count:2,tags_plaintext:""},
			{id:173,person_id:261,location_id:5130,subject:"Travel Insurance",content:"I'm heading to Thailand for the next 6 months. Have a triple entry visa. One of these I intend to use to return to the UK for a friends wedding. Does anyone know of any specific Backpacker \/ Long Term Travel Insurance provider that will allow me to come back for a visit without invalidating the rest of my policy. If not it looks like I'm going to have to get 2 lots!",tags:"",created_at:"2009-02-26 01:41:31",last_answer:"2009-03-11 12:08:19",location_shard:"thailand",answer_count:4,tags_plaintext:""},
			{id:207,person_id:261,location_id:5153,subject:"Does anyone know a good back specialist Chirporactor \/ Osteopath in or around Karbi \/ Ao Nang or Phuket??",content:"Mt mate is bed ridden with a bad back and needs a back specialist. We're in Ao Nang, Krabi Province but can travel to Phuket if needed.",tags:"",created_at:"2009-03-07 11:37:13",last_answer:"2009-03-08 20:52:09",location_shard:"thailand",answer_count:3,tags_plaintext:""},
			{id:210,person_id:11,location_id:5130,subject:"I am looking to travel to the South East Aisa region later in the year, where specifically should I go?",content:"Having not traveled in the region at all I would like to know which countries are the best to experience first? \r\rWould you recommend focusing on one country say Thailand first, I hear you can explore the beautiful tropical waters around Crabbe and Pucket experiencing tremendous diving etc.... I assume there there are many other highlights of the country, what else is a must do while there? \r\rAlso I don't speak any form of Cantonese or the like, is this an issue?",tags:"dive",created_at:"2009-03-08 14:23:37",last_answer:"2009-03-17 01:33:02",location_shard:"thailand",answer_count:3,tags_plaintext:"diving"},
			{id:261,person_id:524,location_id:5130,subject:"Safety in Thailand...   Also have you got some tips for me to meet people while I'm away?",content:"So I'm travelling o\/s for the first time.. bear with me I'm new at this.. and I'm going by myself to Thailand.  My first impulse is to jump on a tour (like intrepid) so that at least I will have a group of people I'll get to know and maybe make some friendships out of.\r\rBut I'm hearing more and more that I can do this alone.  So, I get off a plane in Bangkok... then what?   And where do I meet fellow likeminded travellers to share experiences with?  And will I feel safe there?\r\rAppreciate your thoughts \/ suggestions \/ advice...",tags:"tour",created_at:"2009-03-23 02:42:15",last_answer:"2009-04-05 10:19:28",location_shard:"thailand",answer_count:6,tags_plaintext:"tours"},
			{id:267,person_id:495,location_id:5130,subject:"Seeking recommendations for good restaurants in Pattaya. (I'll be staying at the Marriott, November 18-22, 2009).",content:"",tags:"restaur",created_at:"2009-03-27 01:33:28",last_answer:"2009-03-27 03:58:44",location_shard:"thailand",answer_count:1,tags_plaintext:"restaurants"},
			{id:357,person_id:261,location_id:5205,subject:"Visa run's from Phuket",content:"Which is the best, easiest, cheapest or quickest Visa run options from Phuket.",tags:"",created_at:"2009-04-30 04:42:49",last_answer:"2010-02-07 22:04:10",location_shard:"thailand",answer_count:3,tags_plaintext:""},
			{id:358,person_id:261,location_id:5205,subject:"Ferry from Phuket to Langkawi",content:"Does anyone know if there is a ferry from Phuket to Langkawi and if so where I would go to book (apart from the port).",tags:"",created_at:"2009-04-30 04:44:11",last_answer:"2009-05-14 04:15:58",location_shard:"thailand",answer_count:2,tags_plaintext:""},
			{id:401,person_id:837,location_id:5156,subject:"I'll be in Thailand for 2 weeks in Dec. Bangkok for first week. What should I do for the next week? I need to get back to Bangkok by the end",content:"I'll be in Bangkok for 2 weeks in December this year. The first week, my wife and I plan to hostel it in Bangkok. But, I've heard that we might not have anything to do for a whole week there. So, I'd like to get out and see what else there is in Thailand. We'll need to get back to Bangkok by the end of our two weeks to fly out, but what could we do for about a week in Thailand? Cheap, cheap, please.",tags:"",created_at:"2009-05-12 05:08:32",last_answer:"2009-05-17 22:57:47",location_shard:"thailand",answer_count:5,tags_plaintext:""},
			{id:460,person_id:10,location_id:5130,subject:"Can I use a camera in public in Thailand?",content:"Are there laws against this, or is it socially frowned upon?",tags:"camera",created_at:"2009-05-14 03:04:58",last_answer:"2009-05-14 21:55:42",location_shard:"thailand",answer_count:4,tags_plaintext:"cameras"},
			{id:475,person_id:779,location_id:5130,subject:"I'm looking for a good place to ride out the economic crisis.  Is Thailand a good place?",content:"If not, what is the best place in the world to lie on the beach while this turmoil is going on around us?",tags:"",created_at:"2009-05-15 12:52:38",last_answer:"2009-06-15 08:04:14",location_shard:"thailand",answer_count:10,tags_plaintext:"beach"},
			{id:540,person_id:974,location_id:5205,subject:"places to go and see at Karon",content:"",tags:"",created_at:"2009-05-25 01:52:02",last_answer:"2009-07-24 23:21:39",location_shard:"thailand",answer_count:3,tags_plaintext:""},
			{id:598,person_id:741,location_id:5244,subject:"What to see in Trang in Thailand? Anyone know Kantang?",content:"Interesting places to see.",tags:"",created_at:"2009-06-02 08:49:01",last_answer:null,location_shard:"thailand",answer_count:0,tags_plaintext:""},
			{id:601,person_id:21,location_id:5130,subject:"Thailand for three weeks in July how much will we need to budget per day?",content:"My fianc\u00c3\u00a9e and I are heading to Thailand for three weeks in July. We plan on traveling about what should budget per day for food, accommodation, activities etc?  We are flying into Phuket then plan on traveling to Bangkok, Chiang Mai, Islands etc",tags:"food budget",created_at:"2009-06-03 00:59:34",last_answer:"2009-06-15 08:17:38",location_shard:"thailand",answer_count:5,tags_plaintext:"budget, food"},
			{id:603,person_id:937,location_id:5156,subject:"Does anyone know of an airline offering cheap return flights from South Africa to Bangkok?",content:"",tags:"",created_at:"2009-06-03 11:24:38",last_answer:"2009-06-08 21:44:16",location_shard:"thailand",answer_count:3,tags_plaintext:"cheap"},
			{id:639,person_id:1044,location_id:5130,subject:"Where can I find good shopping in Phuket? In particular - places that sell imitation handbags?",content:"",tags:"shop",created_at:"2009-06-16 02:06:15",last_answer:"2009-07-02 02:57:51",location_shard:"thailand",answer_count:5,tags_plaintext:"shopping"},
			{id:650,person_id:1052,location_id:5156,subject:"where are high quality  restaurants",content:"high standard, luxury ambiece",tags:"restaur",created_at:"2009-06-19 17:45:04",last_answer:"2009-07-17 10:31:24",location_shard:"thailand",answer_count:3,tags_plaintext:"restaurants"},
			{id:683,person_id:1082,location_id:5130,subject:"Where are some cheap beach huts on quiet beaches or islands.",content:"",tags:"",created_at:"2009-06-24 03:20:10",last_answer:"2009-06-28 08:44:15",location_shard:"thailand",answer_count:1,tags_plaintext:"cheap, beach"},
			{id:693,person_id:1092,location_id:5130,subject:"What is the best way to travel from India to Thailand?",content:"I am starting to plan a couple of weeks holiday from Mumbai to somewhere is Thailand. I am wondering what are the best methods and where are some places to go?",tags:"",created_at:"2009-06-25 09:19:55",last_answer:"2009-07-07 10:48:23",location_shard:"thailand",answer_count:3,tags_plaintext:""},
			{id:737,person_id:1135,location_id:5130,subject:"how much money will i need to stay in south east asia for two months including visa and trains to travell abowt",content:"",tags:"",created_at:"2009-07-14 09:58:14",last_answer:"2009-07-18 12:04:21",location_shard:"thailand",answer_count:4,tags_plaintext:""},
			{id:753,person_id:225,location_id:5164,subject:"where is the best place to stay?",content:"we are a young couple, want a good balance of night life and relaxation",tags:"nightlif",created_at:"2009-07-19 08:31:15",last_answer:"2009-07-23 04:31:02",location_shard:"thailand",answer_count:5,tags_plaintext:"night life"},
			{id:767,person_id:1032,location_id:5130,subject:"Have you ever been on a Gap Adventures Tour? if so, what did you think?",content:"",tags:"",created_at:"2009-07-22 08:47:01",last_answer:"2009-07-28 19:34:09",location_shard:"thailand",answer_count:1,tags_plaintext:""},
			{id:773,person_id:1160,location_id:5205,subject:"Karon Markets - when are the Karon Night Markets",content:"Hi can anyone tell us when the Karon night markets are on in the temple grounds and what types of things they sell?  Also interested in a day 'join in' fishing trip from Chalong - any company you could recommend.  Ska Bar in Kata when is the fire dancing on?  Any good (and cheap) restuarants in Karon and Kata = Thai & seafood mainly?  Any general recommendations or info would be appreciated. Returning on our second trip this October & staying in Karon again.",tags:"fish templ",created_at:"2009-07-24 23:22:02",last_answer:"2009-07-25 10:41:10",location_shard:"thailand",answer_count:1,tags_plaintext:"temples, fishing, cheap"},
			{id:775,person_id:1,location_id:5130,subject:"Boat charter for scuba diving trip?",content:"Has anyone chartered a boat for scuba diving in Thailand? I'm interested in costs for a multi-day trip. Thanks!",tags:"boat scubadiv",created_at:"2009-07-26 05:08:42",last_answer:"2009-07-27 08:37:46",location_shard:"thailand",answer_count:1,tags_plaintext:"boating, scuba diving"},
			{id:784,person_id:702,location_id:55434,subject:"Places to stay, recommendations for things to do....",content:"Three fairly intrepid females, rocking up in Ko Samet for 10 days on 6 August.  We want to be able to laze on a beach, eat good food, have a few drinks, not be smack-bang in a tourist trap area and would love to do some yoga, fishing and Thai cooking.\r\rAny recommendations for places to stay?  Any price range at the moment although the accomodation should have private bathroom, A\/C and be on\/right next to a beach - something like Star Huts on Koh Phanang would be great.\r\rAny recs for fishing trips?  I love sea fishing and would like to do some if possible.\r\rAny yoga and Thai cooking school suggestions?\r\rThanks in advance.",tags:"yoga food fish drink",created_at:"2009-07-29 08:36:35",last_answer:"2009-08-16 11:34:14",location_shard:"thailand",answer_count:1,tags_plaintext:"beach, food, drinking, yoga, fishing"},
			{id:886,person_id:282,location_id:55491,subject:"We are going to do our open water dive course, what is the best company to use? and good value place to stay? cheers",content:"",tags:"dive",created_at:"2009-09-10 12:59:49",last_answer:"2009-12-28 15:01:52",location_shard:"thailand",answer_count:4,tags_plaintext:"diving"},
			{id:892,person_id:598,location_id:5130,subject:"Does anyone know of a good massage school in Thailand?",content:"I want to do a comprehensive professional course that will be accredited in Australia.",tags:"",created_at:"2009-09-12 01:33:57",last_answer:"2009-12-23 18:20:06",location_shard:"thailand",answer_count:1,tags_plaintext:""},
			{id:998,person_id:837,location_id:5130,subject:"I want to tour around Thailand for a week. Any suggested tours that DO NOT include airfare (I'll already be there)?",content:"I'll be in Thailand for 2 weeks. Bangkok for the first week, and then I'm not sure what I'll be doing for the second week. I'd like to tour around the country on a package kind of deal, but I don't want the cost to include airfare. Any ideas on websites I can check out to sign up for something like that?",tags:"tour",created_at:"2009-10-19 17:49:31",last_answer:"2009-10-27 04:42:27",location_shard:"thailand",answer_count:4,tags_plaintext:"tours"},
			{id:1028,person_id:1348,location_id:5141,subject:"I am riding my motorbike from Singapore to Ko Lanta for Christmas. What is there to see and do on the way?",content:"I'm riding up the west coast of Malaysia and will cross into Thailand at Kampung Wang Kelian but can't find too much of interest to do on my way up.\r\rAny ideas travellr's?\r\rCheers\rPlanetraveler",tags:"",created_at:"2009-10-29 13:34:16",last_answer:null,location_shard:"thailand",answer_count:0,tags_plaintext:"motorbike"},
			{id:1097,person_id:520,location_id:5164,subject:"Looking for a quiet(ish) beach resort to stay at around New Year. Any suggestions?",content:"I'm planning a last minute holiday to Thailand & I'm looking for a not too rowdy beach resort to stay at in Koh Samui (or Koh Phi Phi, Koh Lanta) over new year. My only requirements are that it has to have a great pool and excellent beach front. Any tips?",tags:"",created_at:"2009-12-08 07:40:34",last_answer:"2009-12-10 04:37:47",location_shard:"thailand",answer_count:4,tags_plaintext:"beach"},
			{id:1175,person_id:1187,location_id:5156,subject:"Where is a good place to catch a movie in Bangkok?",content:"",tags:"",created_at:"2010-01-04 05:02:49",last_answer:"2010-01-04 16:11:01",location_shard:"thailand",answer_count:1,tags_plaintext:""},
			{id:1192,person_id:1474,location_id:5130,subject:"I want a beach\/near beach rental for 6 months at fair price",content:"Small place OK.  Will bey base to explore all of Thailand. Will schedule slowest months to save costs.  Suggestions?",tags:"beach rent",created_at:"2010-01-06 06:51:02",last_answer:"2010-01-13 11:14:55",location_shard:"thailand",answer_count:1,tags_plaintext:"beaches, rent"},
			{id:1220,person_id:1494,location_id:5130,subject:"Who did you have travel to Thailand in month of May? i need information about wheather",content:"i will travel to Thailand in May, so i need information about the weather and cyclone NARGIS",tags:"weather",created_at:"2010-01-11 11:52:06",last_answer:"2010-02-02 15:06:30",location_shard:"thailand",answer_count:3,tags_plaintext:"weather"},
			{id:1227,person_id:1502,location_id:5205,subject:"How much is the budget for a thirty day stay in phuket thailand?",content:"",tags:"budget",created_at:"2010-01-13 14:56:55",last_answer:"2010-02-06 11:53:15",location_shard:"thailand",answer_count:1,tags_plaintext:"budget"},
			{id:1236,person_id:1141,location_id:5205,subject:"Phuket Thailand",content:"What is the best to see and do while in Phuket - \r\nStaying at Surin Beach for 17 days \r\nBest food and best days trips ?",tags:"",created_at:"2010-01-14 09:54:19",last_answer:"2010-02-06 11:49:43",location_shard:"thailand",answer_count:1,tags_plaintext:""},
			{id:1238,person_id:1509,location_id:5130,subject:"1st time in Thailand for three weeks in Feburary What acitivtys \/ Towns \/Islands \/ Tours are best budget?",content:"",tags:"budget",created_at:"2010-01-14 16:18:59",last_answer:"2010-01-20 21:38:32",location_shard:"thailand",answer_count:6,tags_plaintext:"budget"},
			{id:1239,person_id:1141,location_id:5205,subject:"What can one do in Phuket for 17 days ?",content:"",tags:"",created_at:"2010-01-15 00:41:07",last_answer:"2010-02-09 09:43:17",location_shard:"thailand",answer_count:2,tags_plaintext:""},
			{id:1240,person_id:1509,location_id:5205,subject:"Where can I find a beach  in thailand not on phuket, small quaint",content:"",tags:"beach",created_at:"2010-01-15 00:43:30",last_answer:"2010-02-02 14:57:57",location_shard:"thailand",answer_count:5,tags_plaintext:"beaches"},
			{id:1246,person_id:1509,location_id:5130,subject:"Hill Tribes Selling Hand crafted Silver buttons, beads etc.  Thailand",content:"Feb. 12th I will arrive in BKK for three weeks. First visit.\r\nI would like to visit the Hill Tribes and purchase Hand crafted Silver buttons, beads etc. to bring back to the USA for my Jewelry and beadwork. What area of Thailand and how would I get there? How safe is it doing cash business? Other than US customs is there any local restrictions I should be aware of? Dose any one know of an exporter In the jewelry finding business? That I can do repeat business with after I return to the USA? I plan to spend some time in Chiang Mai, and do a  island stay possibly on Koh Phi Phi. \r\nLooking for any other suggestions for our vacation.\r\nThank You, Harry, from San Francisco.",tags:"craft work",created_at:"2010-01-15 16:56:30",last_answer:"2010-01-16 16:18:14",location_shard:"thailand",answer_count:2,tags_plaintext:"crafts, working"},
			{id:1262,person_id:72,location_id:5130,subject:"what is the best and most interesting way to travell thailand,kambodcha, malaysia?",content:"this november i'm going to thailand, malaysia and maybe kambodcha for 3 to 3and a half weeks. started doing a bit research cause it's my first time going to asia. basicly the route should be bankok-chiang mai-phnom penn(kambodcha)-phuket-kuala lumpur (malaysia). what would be the best way to travell to all these places?? train or plain?",tags:"trek surf",created_at:"2010-01-24 11:34:33",last_answer:"2010-02-02 14:54:08",location_shard:"thailand",answer_count:3,tags_plaintext:"trekking, surfing, sight seeing"},
			{id:1358,person_id:1608,location_id:5130,subject:"where is the best backpacker friendly eco lodge place to stay in pai?",content:"",tags:"",created_at:"2010-02-12 15:18:10",last_answer:null,location_shard:"thailand",answer_count:0,tags_plaintext:""},
			{id:1390,person_id:88,location_id:5205,subject:"Top 5 fun things in Phuket Thailand #fun #Phuket #nonculture",content:"Looking for things that don't involve shopping, museums, movies, eating!",tags:"",created_at:"2010-02-22 06:53:26",last_answer:"2010-02-22 18:18:25",location_shard:"thailand",answer_count:1,tags_plaintext:""},
			{id:1431,person_id:1666,location_id:5156,subject:"how badly do I need an onward ticket to fly into Bangkok?",content:"I fly into Bangkok March 24th and will be traveling around up to Chiang Mai then over to Laos but have no onward ticket to present when I'm flying into Bangkok... I heard this can be a problem. Any suggestions on cheap and\/or refundable tickets I could get just in case?",tags:"ticket fly",created_at:"2010-03-03 05:24:06",last_answer:"2010-03-03 16:45:57",location_shard:"thailand",answer_count:2,tags_plaintext:"tickets, fly"}
		]
});
